from pathlib import Path
p=Path('outputs/portfolio/dist/index.html')
s=p.read_text(encoding='utf-8').replace('#101a19','#fafbff').replace('portrait.jpg','portrait.png').replace('width="300" height="302"','width="768" height="1365" fetchpriority="high"')
s=s.replace('<p class="eyebrow">EDUCATOR · RESEARCHER · DEVELOPER</p>','<p class="eyebrow">HELLO, I’M TAHIR <span aria-hidden="true">✦</span></p>')
s=s.replace('<h1>Muhammad<br>Tahir <em>Mehmood.</em></h1><p class="intro">Teaching ideas.<br>Building possibilities.</p>','<h1>Turning ideas into<br><em>learning.</em><br>And possibilities.</h1><p class="intro">Muhammad Tahir Mehmood</p><p class="role-line">Computer Science Educator <span> / </span> AI Researcher <span> / </span> Developer</p>')
s=s.replace('<span>THEORY → PRACTICE</span><strong>Always learning.<br>Always building.</strong>','<span>BASED IN OKARA, PAKISTAN</span><strong>Educator by passion.<br>Builder by curiosity.</strong>')
s=s.replace('<span>01 / MY FOCUS</span><p>Where education<br>meets technology.</p>','<span>10+ YEARS</span><p>Connecting people<br>and possibilities.</p>')
s=s.replace('<body>','<body><div class="scroll-progress" aria-hidden="true"></div>')
s=s.replace('tm<span>.</span>','tahir<span>.</span>')
s=s.replace('<div class="project-symbol">LMS<span> / </span></div>','<div class="project-symbol">LMS<span>Learning, connected.</span></div>')
s=s.replace('<div class="project-symbol">T<span> / </span>T</div>','<div class="project-symbol">TimeTable<span>A little more organised.</span></div>')
s=s.replace('<div class="project-symbol">AI<span> _ </span></div>','<div class="project-symbol">Artificial Intelligence<span>Explore. Understand. Apply.</span></div>')
s=s.replace('<div class="project-symbol">React<span> { }</span></div>','<div class="project-symbol">React<span>Learn by building.</span></div>')
p.write_text(s,encoding='utf-8')
